server:
  port: 8080
spring:
  application:
    name: mall-copy
  datasource:
    url: jdbc:mysql://localhost:3306/mall_tiny?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: password
  redis:
    host: localhost
    database: 0
    port: 6379
    password:
    timeout: 6000

    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 5000

springfox:
  documentation:
    enabled: true
    open-api:
      enabled: true
    swagger-ui:
      enabled: true


