server:
  port: 8080
spring:
  application:
    name: mall-copy
  datasource:
    url: jdbc:mysql://localhost:3306/mall_tiny?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: localhost
    database: 0
    port: 6379
    password:

